apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: amigoscode/fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-11065-2909-pgsql-primary.servers.linodedb.net:5432/fraud
            - name: SPRING_DATASOURCE_PASSWORD
              value: j+3MtRmJ0mIp8ORH
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraud
